// Canonical USMLE topic taxonomy, transcribed from the official USMLE Content
// Outline (2026), organized by the outline's organ systems. Each entry is a
// specific testable condition (leaf item). Names are normalized to canonical
// disease names (the source PDF had OCR artifacts).
//
// The planner picks ONE topic from this list per question (adaptively, weighted
// toward weak topics) and passes it to the generator, so topics are canonical
// and mastery accumulates per condition.

export const OUTLINE_TOPICS = {
  'human-development': [
    'Constitutional growth delay', 'Primary nocturnal enuresis', 'Failure to thrive',
    'Adolescent gynecomastia', 'Delayed puberty', 'Precocious puberty',
    'Normal developmental milestones', 'Normal age-related (geriatric) changes', 'Polypharmacy in the elderly',
  ],

  immune: [
    'Common variable immunodeficiency', 'Hyper-IgM syndrome', 'X-linked agammaglobulinemia (Bruton)',
    'Selective IgA deficiency', 'Adenosine deaminase deficiency SCID', 'DiGeorge syndrome (22q11.2 deletion)',
    'Severe combined immunodeficiency', 'Wiskott-Aldrich syndrome', 'Chronic granulomatous disease',
    'Chediak-Higashi syndrome', 'Leukocyte adhesion deficiency', 'C1 esterase inhibitor deficiency (hereditary angioedema)',
    'Terminal complement deficiency', 'Mannose-binding lectin deficiency', 'HIV infection', 'AIDS-defining illness',
    'Immune reconstitution inflammatory syndrome', 'Kaposi sarcoma', 'Type I hypersensitivity / anaphylaxis',
    'Type II hypersensitivity reaction', 'Type III hypersensitivity / serum sickness', 'Type IV hypersensitivity reaction',
    'Hyperacute transplant rejection', 'Acute transplant rejection', 'Chronic transplant rejection',
    'Graft-versus-host disease',
  ],

  blood: [
    'Malaria', 'Babesiosis', 'Dengue fever', 'Ebola virus disease', 'Cat-scratch disease', 'Bubonic plague',
    'Autoimmune hemolytic anemia (warm)', 'Cold agglutinin disease', 'Paroxysmal nocturnal hemoglobinuria',
    'Thrombotic thrombocytopenic purpura', 'Hemolytic uremic syndrome', 'Cryoglobulinemia',
    'Acute lymphoblastic leukemia', 'Acute myeloid leukemia', 'Chronic lymphocytic leukemia',
    'Chronic myeloid leukemia', 'Hodgkin lymphoma', 'Non-Hodgkin lymphoma', 'Burkitt lymphoma',
    'Cutaneous T-cell lymphoma', 'Multiple myeloma', 'Monoclonal gammopathy of undetermined significance',
    'Waldenstrom macroglobulinemia', 'Myelofibrosis', 'Myelodysplastic syndrome', 'Anemia of chronic disease',
    'Iron deficiency anemia', 'G6PD deficiency', 'Pyruvate kinase deficiency', 'Hereditary spherocytosis',
    'Hereditary elliptocytosis', 'Sickle cell disease', 'Alpha-thalassemia', 'Beta-thalassemia',
    'Sideroblastic anemia', 'Congenital methemoglobinemia', 'Megaloblastic anemia (B12/folate)', 'Aplastic anemia',
    'Cyclic neutropenia', 'Immune thrombocytopenic purpura', 'Polycythemia vera', 'Secondary polycythemia',
    'Disseminated intravascular coagulation', 'Hemophilia A', 'Hemophilia B', 'von Willebrand disease',
    'Heparin-induced thrombocytopenia', 'Antithrombin III deficiency', 'Protein C deficiency', 'Protein S deficiency',
    'Factor V Leiden', 'Prothrombin G20210A mutation', 'Antiphospholipid antibody syndrome',
    'ABO incompatibility transfusion reaction', 'Delayed hemolytic transfusion reaction',
    'Transfusion-related acute lung injury (TRALI)', 'Post-splenectomy sepsis', 'Tumor lysis syndrome',
    'Warfarin-induced skin necrosis',
  ],

  behavioral: [
    'Schizophrenia', 'Schizoaffective disorder', 'Brief psychotic disorder', 'Delusional disorder',
    'Substance-induced psychotic disorder', 'Generalized anxiety disorder', 'Panic disorder',
    'Obsessive-compulsive disorder', 'Post-traumatic stress disorder', 'Acute stress disorder', 'Social anxiety disorder',
    'Specific phobia', 'Separation anxiety disorder', 'Major depressive disorder', 'Postpartum depression',
    'Persistent depressive disorder', 'Bipolar I disorder', 'Bipolar II disorder', 'Cyclothymic disorder',
    'Premenstrual dysphoric disorder', 'Suicidal ideation', 'Conversion disorder (functional neurologic symptom disorder)',
    'Somatic symptom disorder', 'Illness anxiety disorder', 'Malingering', 'Factitious disorder', 'Dissociative disorders',
    'Anorexia nervosa', 'Bulimia nervosa', 'Binge-eating disorder', 'Attention-deficit/hyperactivity disorder',
    'Autism spectrum disorder', 'Oppositional defiant disorder', 'Conduct disorder', 'Tourette disorder',
    'Antisocial personality disorder', 'Borderline personality disorder', 'Narcissistic personality disorder',
    'Histrionic personality disorder', 'Avoidant personality disorder', 'Schizotypal personality disorder',
    'Adjustment disorder', 'Normal grief vs. persistent complex bereavement', 'Gender dysphoria',
    'Alcohol use disorder / withdrawal', 'Opioid use disorder / withdrawal', 'Benzodiazepine withdrawal',
    'Cocaine intoxication / withdrawal', 'Cannabis use disorder', 'Nicotine dependence',
  ],

  nervous: [
    'Bacterial meningitis', 'Viral (aseptic) meningitis', 'Herpes simplex encephalitis', 'Cryptococcal meningitis',
    'Neurosyphilis', 'Lyme neuroborreliosis', 'Creutzfeldt-Jakob disease', 'Botulism', 'Tetanus',
    'Progressive multifocal leukoencephalopathy', 'Myasthenia gravis', 'Multiple sclerosis', 'Transverse myelitis',
    'Meningioma', 'Glioblastoma', 'Medulloblastoma', 'Primary CNS lymphoma', 'Brain metastases', 'Schwannoma (acoustic neuroma)',
    'Transient ischemic attack', 'Ischemic stroke', 'Embolic stroke', 'Intracerebral hemorrhage',
    'Subarachnoid hemorrhage', 'Carotid artery stenosis', 'Vertebral artery dissection', 'Cerebral venous sinus thrombosis',
    'Vascular dementia', 'Cauda equina syndrome', 'Spinal cord compression', 'Spinal stenosis', 'Syringomyelia',
    'Bell palsy', 'Horner syndrome', 'Internuclear ophthalmoplegia', 'Guillain-Barre syndrome', 'Miller Fisher syndrome',
    'Charcot-Marie-Tooth disease', 'Carpal tunnel syndrome', 'Herpes zoster / postherpetic neuralgia',
    'Complex regional pain syndrome', 'Trigeminal neuralgia', 'Alzheimer disease', 'Frontotemporal dementia',
    'Lewy body dementia', 'Delirium', 'Brain death / coma', 'Amyotrophic lateral sclerosis',
    'Duchenne muscular dystrophy', 'Myotonic dystrophy', 'Essential tremor', 'Parkinson disease', 'Huntington disease',
    'Acute dystonic reaction', 'Migraine headache', 'Cluster headache', 'Tension headache',
    'Generalized tonic-clonic seizure', 'Absence seizure', 'Febrile seizure', 'Narcolepsy / cataplexy',
    'Restless legs syndrome', 'Obstructive sleep apnea', 'Epidural hematoma', 'Subdural hematoma', 'Concussion',
    'Idiopathic intracranial hypertension', 'Normal-pressure hydrocephalus', 'Neural tube defects', 'Tuberous sclerosis',
    'Von Hippel-Lindau disease', 'Sturge-Weber syndrome', 'Arnold-Chiari malformation', 'Neuroleptic malignant syndrome',
    'Serotonin syndrome', 'Tardive dyskinesia',
    'Conjunctivitis', 'Bacterial keratitis', 'Uveitis', 'Orbital cellulitis', 'Optic neuritis', 'Retinoblastoma',
    'Ocular melanoma', 'Cataract', 'Open-angle glaucoma', 'Acute angle-closure glaucoma', 'Amblyopia', 'Strabismus',
    'Hypertensive retinopathy', 'Age-related macular degeneration', 'Papilledema', 'Retinal detachment',
    'Central retinal artery occlusion', 'Central retinal vein occlusion', 'Amaurosis fugax', 'Orbital fracture',
    'Hyphema', 'Otitis media', 'Otitis externa', 'Cholesteatoma', 'Otosclerosis', 'Noise-induced hearing loss',
    'Meniere disease', 'Benign paroxysmal positional vertigo', 'Vestibular neuritis', 'Tympanic membrane perforation',
  ],

  skin: [
    'Cellulitis', 'Erysipelas', 'Impetigo', 'Staphylococcal scalded skin syndrome', 'Necrotizing fasciitis',
    'Cutaneous abscess', 'Folliculitis', 'Scarlet fever', 'Herpes simplex (cutaneous)', 'Herpes zoster',
    'Molluscum contagiosum', 'Hand-foot-and-mouth disease', 'Erythema infectiosum (fifth disease)', 'Measles',
    'Roseola infantum', 'Verruca vulgaris', 'Cutaneous candidiasis', 'Tinea corporis', 'Onychomycosis', 'Scabies',
    'Pediculosis (lice)', 'Psoriasis', 'Lichen planus', 'Allergic contact dermatitis', 'Pemphigus vulgaris',
    'Bullous pemphigoid', 'Dermatitis herpetiformis', 'Pyoderma gangrenosum', 'Erythema nodosum', 'Atopic dermatitis',
    'Pityriasis rosea', 'Urticaria', 'Stevens-Johnson syndrome / toxic epidermal necrolysis', 'Erythema multiforme',
    'Vitiligo', 'Actinic keratosis', 'Seborrheic keratosis', 'Basal cell carcinoma', 'Squamous cell carcinoma',
    'Melanoma', 'Mycosis fungoides', 'Alopecia areata', 'Acne vulgaris', 'Hidradenitis suppurativa', 'Rosacea',
    'Aphthous ulcers', 'Oral leukoplakia', 'Albinism', 'Decubitus ulcer', 'Frostbite', 'Keloid', 'Xeroderma pigmentosum',
  ],

  musculoskeletal: [
    'Osteomyelitis', 'Septic arthritis', 'Necrotizing fasciitis', 'Gas gangrene (clostridial myonecrosis)',
    'Ankylosing spondylitis', 'Dermatomyositis / polymyositis', 'Juvenile idiopathic arthritis', 'Rheumatoid arthritis',
    'Psoriatic arthritis', 'Adhesive capsulitis (frozen shoulder)', 'Bursitis', 'Ganglion cyst',
    'Temporomandibular joint disorder', 'Tendinitis', 'Osteoid osteoma', 'Osteosarcoma', 'Ewing sarcoma',
    'Rhabdomyosarcoma', 'Metastatic bone disease', 'Chondromalacia patellae', 'Herniated intervertebral disc',
    'Legg-Calve-Perthes disease', 'Osgood-Schlatter disease', 'Osteomalacia', 'Osteonecrosis (avascular necrosis)',
    'Osteoporosis', 'Paget disease of bone', 'Pathologic fracture', 'Spondylolisthesis', 'Gout', 'Pseudogout',
    'Osteoarthritis', 'Dupuytren contracture', 'Rhabdomyolysis', 'Compartment syndrome', 'Low back pain',
    'Rotator cuff tear', 'Slipped capital femoral epiphysis', 'Developmental dysplasia of the hip', 'Scoliosis',
    'Achondroplasia', 'Osteogenesis imperfecta', 'McArdle disease', 'Statin-induced myopathy', 'Malignant hyperthermia',
  ],

  cardiovascular: [
    'Infective endocarditis', 'Myocarditis', 'Atherosclerosis', 'Cardiac myxoma',
    'Premature ventricular complexes', 'Atrial fibrillation', 'Atrial flutter', 'Multifocal atrial tachycardia',
    'Paroxysmal supraventricular tachycardia', 'Ventricular tachycardia', 'Ventricular fibrillation',
    'Torsades de pointes', 'First-degree AV block', 'Second-degree AV block (Mobitz I)', 'Second-degree AV block (Mobitz II)',
    'Third-degree (complete) AV block', 'Left bundle branch block', 'Right bundle branch block', 'Sick sinus syndrome',
    'Long QT syndrome', 'Wolff-Parkinson-White syndrome', 'Congestive heart failure', 'Cor pulmonale',
    'Diastolic heart failure', 'High-output heart failure', 'Cardiogenic pulmonary edema', 'Acute coronary syndrome',
    'ST-elevation myocardial infarction', 'NSTEMI', 'Stable angina', 'Unstable angina', 'Prinzmetal (vasospastic) angina',
    'Dilated cardiomyopathy', 'Takotsubo cardiomyopathy', 'Hypertrophic cardiomyopathy', 'Restrictive cardiomyopathy',
    'Hypertensive heart disease', 'Papillary muscle rupture', 'Ventricular free wall rupture',
    'Acute pericarditis', 'Constrictive pericarditis', 'Pericardial effusion', 'Cardiac tamponade',
    'Mitral stenosis', 'Mitral regurgitation', 'Mitral valve prolapse', 'Aortic stenosis', 'Aortic regurgitation',
    'Tricuspid regurgitation', 'Rheumatic heart disease', 'Orthostatic hypotension', 'Essential hypertension',
    'Hypertensive emergency', 'Secondary hypertension', 'Familial hypercholesterolemia', 'Hypertriglyceridemia',
    'Abdominal aortic aneurysm', 'Thoracic aortic aneurysm', 'Aortic dissection', 'Peripheral arterial disease',
    'Thromboangiitis obliterans (Buerger disease)', 'Cholesterol embolization', 'Deep venous thrombosis',
    'Superficial thrombophlebitis', 'Varicose veins', 'Chronic venous insufficiency', 'Atrial septal defect',
    'Ventricular septal defect', 'Patent ductus arteriosus', 'Coarctation of the aorta', 'Tetralogy of Fallot',
    'Transposition of the great arteries', 'Patent foramen ovale', 'Anomalous left coronary artery',
  ],

  respiratory: [
    'Acute sinusitis', 'Epiglottitis', 'Croup', 'Pertussis', 'Streptococcal pharyngitis', 'Peritonsillar abscess',
    'Allergic rhinitis', 'Community-acquired pneumonia', 'Hospital-acquired pneumonia', 'Aspiration pneumonia',
    'Pneumocystis jirovecii pneumonia', 'Pulmonary tuberculosis', 'Lung abscess', 'Allergic bronchopulmonary aspergillosis',
    'Histoplasmosis', 'Coccidioidomycosis', 'Vocal cord polyps', 'Solitary pulmonary nodule', 'Laryngeal carcinoma',
    'Squamous cell lung carcinoma', 'Lung adenocarcinoma', 'Small cell lung carcinoma', 'Bronchial carcinoid tumor',
    'Mesothelioma', 'Asthma', 'Bronchiectasis', 'Chronic obstructive pulmonary disease', 'Asbestosis', 'Silicosis',
    'Berylliosis', 'Hypersensitivity pneumonitis', 'Idiopathic pulmonary fibrosis', 'Sarcoidosis',
    'Acute respiratory distress syndrome', 'Pulmonary hypertension', 'Pulmonary embolism', 'Fat embolism syndrome',
    'Cardiogenic vs noncardiogenic pulmonary edema', 'Obstructive sleep apnea', 'Obesity hypoventilation syndrome',
    'Pleural effusion', 'Empyema', 'Pneumothorax', 'Tension pneumothorax', 'Hemothorax', 'Atelectasis',
    'Epistaxis', 'Foreign body aspiration', 'Tracheoesophageal fistula', 'Cystic fibrosis (pulmonary)',
    'Neonatal respiratory distress syndrome', 'Amiodarone pulmonary toxicity',
  ],

  gastrointestinal: [
    'Clostridioides difficile colitis', 'Bacterial gastroenteritis', 'Traveler’s diarrhea', 'Spontaneous bacterial peritonitis',
    'Viral hepatitis A', 'Viral hepatitis B', 'Viral hepatitis C', 'CMV / HSV esophagitis', 'Giardiasis',
    'Entamoeba histolytica (amebiasis)', 'Oral candidiasis (thrush)', 'Autoimmune hepatitis', 'Celiac disease',
    'Eosinophilic esophagitis', 'Crohn disease', 'Ulcerative colitis', 'Toxic megacolon', 'Microscopic colitis',
    'Colonic polyps', 'Barrett esophagus', 'Esophageal squamous cell carcinoma', 'Esophageal adenocarcinoma',
    'Zollinger-Ellison syndrome', 'Gastric adenocarcinoma', 'Gastric MALT lymphoma', 'Colorectal cancer',
    'Familial adenomatous polyposis', 'Peutz-Jeghers syndrome', 'Hereditary nonpolyposis colorectal cancer',
    'Carcinoid tumor / carcinoid syndrome', 'Cholangiocarcinoma', 'Hepatocellular carcinoma', 'Pancreatic adenocarcinoma',
    'Achalasia', 'Zenker diverticulum', 'Gastroesophageal reflux disease', 'Mallory-Weiss syndrome', 'Hiatal hernia',
    'Esophageal stricture', 'Peptic ulcer disease', 'Gastritis', 'Gastroparesis', 'Acute appendicitis', 'Angiodysplasia',
    'Diverticulitis', 'Diverticulosis', 'Hirschsprung disease', 'Small bowel obstruction', 'Intussusception',
    'Irritable bowel syndrome', 'Acute mesenteric ischemia', 'Ischemic colitis', 'Necrotizing enterocolitis',
    'Paralytic ileus', 'Volvulus', 'Lactose intolerance', 'Anal fissure', 'Anorectal abscess', 'Hemorrhoids',
    'Cirrhosis', 'Gilbert syndrome', 'Crigler-Najjar syndrome', 'Hepatic encephalopathy', 'Alcoholic hepatitis',
    'Non-alcoholic fatty liver disease', 'Hepatorenal syndrome', 'Portal hypertension / esophageal varices',
    'Choledocholithiasis', 'Ascending cholangitis', 'Cholelithiasis / cholecystitis', 'Primary biliary cholangitis',
    'Primary sclerosing cholangitis', 'Acute pancreatitis', 'Chronic pancreatitis', 'Pancreatic pseudocyst', 'Ascites',
    'Boerhaave syndrome', 'Inguinal hernia', 'Pyloric stenosis', 'Biliary atresia', 'Meckel diverticulum',
    'Acetaminophen hepatotoxicity',
  ],

  renal: [
    'Pyelonephritis', 'Perinephric abscess', 'Cystitis', 'Urethritis', 'Poststreptococcal glomerulonephritis',
    'IgA nephropathy', 'Lupus nephritis', 'Minimal change disease', 'Focal segmental glomerulosclerosis',
    'Membranous nephropathy', 'Alport syndrome', 'Thin basement membrane disease', 'Goodpasture syndrome',
    'Acute tubular necrosis', 'Acute interstitial nephritis', 'Renal papillary necrosis', 'Polycystic kidney disease',
    'Wilms tumor', 'Renal cell carcinoma', 'Bladder (urothelial) carcinoma', 'Acute kidney injury',
    'Chronic kidney disease', 'Diabetic nephropathy', 'Hypertensive nephrosclerosis', 'Nephrolithiasis',
    'Renal tubular acidosis', 'Fanconi syndrome', 'Renal artery stenosis', 'Renal vein thrombosis',
    'Neurogenic bladder', 'Obstructive uropathy / BPH', 'Posterior urethral valves', 'Vesicoureteral reflux',
    'Horseshoe kidney', 'Contrast-induced nephropathy', 'Aminoglycoside nephrotoxicity',
  ],

  pregnancy: [
    'Ectopic pregnancy', 'Spontaneous abortion', 'Gestational diabetes', 'Preeclampsia', 'Eclampsia', 'HELLP syndrome',
    'Gestational hypertension', 'Placenta previa', 'Placental abruption', 'Placenta accreta', 'Hyperemesis gravidarum',
    'Rh isoimmunization', 'Fetal growth restriction', 'Intrahepatic cholestasis of pregnancy', 'Multiple gestation',
    'Cervical insufficiency', 'Preterm labor', 'Premature rupture of membranes', 'Shoulder dystocia', 'Cord prolapse',
    'Breech presentation', 'Postpartum hemorrhage', 'Uterine atony', 'Retained products of conception',
    'Postpartum endometritis', 'Postpartum (peripartum) cardiomyopathy', 'Mastitis', 'Gestational trophoblastic disease',
    'Neonatal respiratory distress syndrome', 'Meconium aspiration syndrome', 'Neonatal sepsis',
    'Neonatal hyperbilirubinemia (jaundice)', 'Neonatal hypoglycemia', 'Sudden infant death syndrome',
    'Congenital TORCH infection', 'Fetal alcohol syndrome', 'Neonatal abstinence syndrome',
  ],

  'female-repro': [
    'Bacterial vaginosis', 'Vulvovaginal candidiasis', 'Trichomoniasis', 'Pelvic inflammatory disease',
    'Tubo-ovarian abscess', 'Gonorrhea', 'Chlamydial cervicitis', 'Genital herpes', 'Syphilis',
    'Human papillomavirus / genital warts', 'Lichen sclerosus', 'Bartholin gland cyst/abscess', 'Leiomyoma (uterine fibroids)',
    'Ovarian cyst', 'Cervical dysplasia', 'Cervical cancer', 'Endometrial hyperplasia', 'Endometrial carcinoma',
    'Ovarian cancer', 'Vulvar carcinoma', 'Female infertility', 'Turner syndrome', 'Primary amenorrhea',
    'Secondary amenorrhea', 'Abnormal uterine bleeding', 'Dysmenorrhea', 'Endometriosis', 'Polycystic ovary syndrome',
    'Premature ovarian insufficiency', 'Menopause / vasomotor symptoms', 'Postmenopausal bleeding', 'Ovarian torsion',
    'Asherman syndrome', 'Breast abscess', 'Fibroadenoma', 'Fibrocystic breast changes', 'Intraductal papilloma',
    'Breast cancer', 'Paget disease of the breast',
  ],

  'male-repro': [
    'Epididymitis', 'Orchitis', 'Acute prostatitis', 'Balanitis', 'Gonococcal urethritis', 'Nongonococcal urethritis',
    'Penile carcinoma', 'Prostate cancer', 'Testicular cancer', 'Erectile dysfunction', 'Male factor infertility',
    'Priapism', 'Benign prostatic hyperplasia', 'Hydrocele', 'Varicocele', 'Spermatocele', 'Testicular torsion',
    'Peyronie disease', 'Phimosis', 'Hypospadias', 'Klinefelter syndrome', 'Cryptorchidism (undescended testis)',
  ],

  endocrine: [
    'Type 1 diabetes mellitus', 'Type 2 diabetes mellitus', 'Diabetic ketoacidosis', 'Hyperosmolar hyperglycemic state',
    'Hypoglycemia', 'Insulinoma', 'Glucagonoma', 'Somatostatinoma', 'Hashimoto thyroiditis', 'Graves disease',
    'Thyroid storm', 'Subacute (de Quervain) thyroiditis', 'Toxic multinodular goiter', 'Euthyroid sick syndrome',
    'Papillary thyroid carcinoma', 'Medullary thyroid carcinoma', 'Anaplastic thyroid carcinoma',
    'Primary hyperparathyroidism', 'Secondary hyperparathyroidism', 'Hypoparathyroidism', 'Addison disease',
    'Secondary adrenal insufficiency', 'Cushing syndrome', 'Primary hyperaldosteronism (Conn syndrome)',
    'Pheochromocytoma', 'Adrenal incidentaloma', 'Congenital adrenal hyperplasia', 'Acromegaly', 'Central diabetes insipidus',
    'Nephrogenic diabetes insipidus', 'SIADH', 'Sheehan syndrome', 'Pituitary apoplexy', 'Prolactinoma', 'Panhypopituitarism',
    'Multiple endocrine neoplasia type 1', 'Multiple endocrine neoplasia type 2', 'Androgen insensitivity syndrome',
    'Congenital hypothyroidism (cretinism)',
  ],

  multisystem: [
    'Lyme disease', 'Rocky Mountain spotted fever', 'Ehrlichiosis / anaplasmosis', 'Brucellosis', 'Leptospirosis',
    'Tularemia', 'Q fever', 'Toxic shock syndrome', 'Infectious mononucleosis (EBV)', 'Disseminated histoplasmosis',
    'Coccidioidomycosis', 'Blastomycosis', 'Visceral leishmaniasis', 'Chagas disease', 'Schistosomiasis',
    'Acute rheumatic fever', 'Systemic lupus erythematosus', 'Sjogren syndrome', 'Systemic sclerosis (scleroderma)',
    'Mixed connective tissue disease', 'Polyarteritis nodosa', 'Granulomatosis with polyangiitis',
    'Eosinophilic granulomatosis with polyangiitis (Churg-Strauss)', 'Giant cell (temporal) arteritis',
    'Polymyalgia rheumatica', 'Takayasu arteritis', 'Kawasaki disease', 'IgA vasculitis (Henoch-Schonlein purpura)',
    'Behcet syndrome', 'Raynaud phenomenon', 'Sarcoidosis', 'Familial Mediterranean fever',
    'Hypercalcemia of malignancy (PTHrP)', 'Lambert-Eaton myasthenic syndrome', 'Paraneoplastic SIADH',
    'Acanthosis nigricans', 'Langerhans cell histiocytosis', 'Protein-calorie malnutrition (kwashiorkor/marasmus)',
    'Thiamine deficiency (Wernicke-Korsakoff)', 'Vitamin B12 deficiency', 'Vitamin C deficiency (scurvy)',
    'Vitamin D deficiency (rickets)', 'Vitamin A deficiency/toxicity', 'Obesity', 'Hyponatremia', 'Hypernatremia',
    'Hypokalemia', 'Hyperkalemia', 'Hypocalcemia', 'Hypercalcemia', 'Metabolic acidosis', 'Metabolic alkalosis',
    'Respiratory acidosis', 'Respiratory alkalosis', 'Heat stroke', 'Hypothermia', 'Carbon monoxide poisoning',
    'Lead poisoning', 'Methanol/ethylene glycol poisoning', 'Salicylate poisoning', 'Acetaminophen poisoning',
    'Organophosphate poisoning', 'Snake envenomation', 'Anaphylactic shock', 'Septic shock', 'Hypovolemic shock',
    'Cardiogenic shock', 'Down syndrome', 'Prader-Willi syndrome', 'Beckwith-Wiedemann syndrome', 'Fragile X syndrome',
    'Marfan syndrome', 'Ehlers-Danlos syndrome', 'Alpha-1 antitrypsin deficiency', 'Hemochromatosis', 'Wilson disease',
    'Cystic fibrosis', 'Tay-Sachs disease', 'Fabry disease', 'Maple syrup urine disease', 'Amyloidosis',
    'Kartagener syndrome (primary ciliary dyskinesia)', 'Acute intermittent porphyria', 'Non-accidental trauma (child abuse)',
    'Intimate partner violence', 'Elder abuse',
  ],

  nutrition: [
    'Protein-calorie malnutrition (kwashiorkor)', 'Protein-calorie malnutrition (marasmus)',
    'Vitamin A deficiency', 'Vitamin A toxicity', 'Thiamine (B1) deficiency (Wernicke-Korsakoff/beriberi)',
    'Niacin (B3) deficiency (pellagra)', 'Pyridoxine (B6) deficiency', 'Folate (B9) deficiency',
    'Vitamin B12 (cobalamin) deficiency', 'Vitamin C deficiency (scurvy)', 'Vitamin D deficiency (rickets/osteomalacia)',
    'Vitamin E deficiency', 'Vitamin K deficiency', 'Zinc deficiency', 'Iron overload / hemochromatosis',
    'Obesity', 'Refeeding syndrome', 'Total parenteral nutrition complications', 'Dietary counseling / lifestyle modification',
  ],

  biostatistics: [
    'Incidence vs prevalence', 'Sensitivity and specificity', 'Positive and negative predictive value',
    'Likelihood ratios / Bayes theorem', 'ROC curve interpretation', 'Relative risk', 'Odds ratio', 'Hazard ratio',
    'Number needed to treat / harm', 'Attributable risk', 'Absolute risk reduction', 'Case-control study',
    'Cohort study', 'Cross-sectional study', 'Randomized controlled trial', 'Meta-analysis / systematic review',
    'Confounding bias', 'Selection bias', 'Recall bias', 'Lead-time bias', 'Length-time bias', 'Measurement bias',
    'Type I error (alpha)', 'Type II error (beta) and power', 'Confidence intervals', 'p-value interpretation',
    't-test', 'Chi-square test', 'ANOVA', 'Correlation and regression', 'Kaplan-Meier survival analysis',
    'Measures of central tendency / distribution', 'Intention-to-treat analysis', 'Internal vs external validity',
    'Screening test criteria', 'Phases of clinical trials', 'Informed consent for research', 'Institutional review board',
  ],

  'social-sciences': [
    'Informed consent', 'Decision-making capacity', 'Informed refusal', 'Involuntary psychiatric admission',
    'Advance directives / health care proxy', 'Brain death determination', 'Organ donation', 'Hospice / palliative care',
    'Confidentiality and HIPAA', 'Duty to warn (Tarasoff)', 'Mandatory reporting of abuse', 'Reporting impaired physician',
    'Medical error disclosure', 'Truth-telling', 'Conflict of interest', 'Physician-patient boundaries',
    'Breaking bad news', 'Use of a medical interpreter', 'Root cause analysis', 'Failure mode and effects analysis',
    'Swiss cheese model of error', 'Active vs latent error', 'Near-miss event', 'Medication reconciliation',
    'Handoff communication', 'Universal protocol (time-out)', 'Wrong-site surgery', 'Central line-associated bloodstream infection',
    'Catheter-associated UTI', 'Hand hygiene / nosocomial infection', 'PDSA cycle (quality improvement)',
    'High-reliability organization', 'Health care disparities', 'EMTALA', 'Types of insurance (Medicare/Medicaid)',
  ],
};

// Map each blueprint system key (across all Steps) to the outline categories it
// draws topics from.
export const SYSTEM_TO_OUTLINE = {
  'repro-endo': ['female-repro', 'male-repro', 'endocrine', 'pregnancy'],
  'resp-renal': ['respiratory', 'renal'],
  'behavioral-nervous': ['behavioral', 'nervous'],
  'blood-immune': ['blood', 'immune'],
  'immune-blood': ['immune', 'blood'],
  'msk-skin': ['musculoskeletal', 'skin'],
  msk: ['musculoskeletal'],
  skin: ['skin'],
  multisystem: ['multisystem'],
  nutrition: ['nutrition'],
  cardiovascular: ['cardiovascular'],
  gastrointestinal: ['gastrointestinal'],
  biostats: ['biostatistics'],
  'human-development': ['human-development'],
  'renal-repro': ['renal', 'female-repro', 'male-repro'],
  'renal-male-repro': ['renal', 'male-repro'],
  behavioral: ['behavioral'],
  nervous: ['nervous'],
  respiratory: ['respiratory'],
  endocrine: ['endocrine'],
  pregnancy: ['pregnancy'],
  'pregnancy-repro': ['pregnancy', 'female-repro', 'male-repro'],
  'social-sciences': ['social-sciences'],
};

// Topic pool for a blueprint system key (union of its outline categories).
export const topicsForSystem = (systemKey) => {
  const cats = SYSTEM_TO_OUTLINE[systemKey] || [];
  const pool = [];
  cats.forEach((c) => (OUTLINE_TOPICS[c] || []).forEach((t) => pool.push(t)));
  return pool.length ? pool : ['General principles'];
};
